/**
 * Bundled background registry for the merge tools' DesignPanel. Files are
 * small vector PDFs generated by `scripts/gen-backgrounds.mjs` into
 * `public/backgrounds/<tool>/`, each with a same-basename PNG thumbnail so
 * the picker never rasterizes at runtime. Mirrors `designer-fonts.ts`:
 * static registry, fetch-on-demand, in-memory memo cache.
 */
import type { DocumentSpec } from "@event-editor/core/merge";

export interface ToolBackground {
  id: string;
  label: string;
  file: string;
  tool: "certificate" | "ticket";
}

export const TOOL_BACKGROUNDS: ToolBackground[] = [
  { id: "cert-double-rule", label: "Double rule", file: "cert-double-rule.pdf", tool: "certificate" },
  { id: "cert-bottom-bar", label: "Bottom bar", file: "cert-bottom-bar.pdf", tool: "certificate" },
  { id: "cert-corner-rules", label: "Corner rules", file: "cert-corner-rules.pdf", tool: "certificate" },
  { id: "cert-head-rule", label: "Head rule", file: "cert-head-rule.pdf", tool: "certificate" },
  { id: "ticket-stub", label: "Stub band", file: "ticket-stub.pdf", tool: "ticket" },
  { id: "ticket-top-band", label: "Top band", file: "ticket-top-band.pdf", tool: "ticket" },
  { id: "ticket-thin-border", label: "Thin border", file: "ticket-thin-border.pdf", tool: "ticket" },
  { id: "ticket-corner-ticks", label: "Corner ticks", file: "ticket-corner-ticks.pdf", tool: "ticket" },
];

/** Bundled backgrounds available for a tool ([] for tools without any). */
export function backgroundsForTool(tool: string): ToolBackground[] {
  return TOOL_BACKGROUNDS.filter((b) => b.tool === tool);
}

/** Public URL of a background's picker thumbnail (same basename, .png). */
export function backgroundThumbUrl(entry: ToolBackground): string {
  return `/backgrounds/${entry.tool}/${entry.file.replace(/\.pdf$/, ".png")}`;
}

function toBase64(bytes: Uint8Array): string {
  let bin = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(bin);
}

const backgroundCache = new Map<string, NonNullable<DocumentSpec["background"]>>();

/**
 * Fetches a bundled background's PDF by registry id and returns it in the
 * `DocumentSpec.background` shape (`kind: "pdf"`, plain base64 src, the
 * `assetSrc` convention from lib/custom-upload.ts). Memoised per id.
 */
export async function loadBackgroundById(id: string): Promise<NonNullable<DocumentSpec["background"]>> {
  const cached = backgroundCache.get(id);
  if (cached) return cached;

  const entry = TOOL_BACKGROUNDS.find((b) => b.id === id);
  if (!entry) {
    throw new Error(`Unknown background id: ${id}`);
  }

  const res = await fetch(`/backgrounds/${entry.tool}/${entry.file}`);
  if (!res.ok) {
    throw new Error(`Failed to load background "${id}": ${res.status} ${res.statusText}`);
  }
  const bytes = new Uint8Array(await res.arrayBuffer());
  const background = { kind: "pdf" as const, src: toBase64(bytes) };
  backgroundCache.set(id, background);
  return background;
}
